apiVersion: v1
kind: Service
metadata:
  name: supplier-service-new
spec:
  type: ClusterIP
  ports:
    - name: rest
        port: 8082
        targetPort: 8082
    - name: grpc
        port: 9093
        targetPort: 9093
  selector:
    app: supplier-service-new
