apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-service-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplier-service-new
  template:
    metadata:
      labels:
        app: supplier-service-new
    spec:
      containers:
        - image: mariiamarafiievych/supplier-service-new
          name: supplier-service-new
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082