apiVersion: v1
kind: Service
metadata:
  name: supplier-service-new
spec:
  type: ClusterIP
  ports:
    - name: "supplier-service-new"
      port: 8082
      targetPort: 8082
  selector:
    app: supplier-service-new
